name: Bug Report
about: Create a report to help us improve
title: "[BUG] "
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        ### Describe the Bug
        A clear and concise description of what the bug is.
  - type: textarea
    id: bug_description
    attributes:
      label: Bug Description
      placeholder: Describe the bug clearly here.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ### Steps to Reproduce
        Steps to reproduce the behavior.
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps
      placeholder: 1. Go to '...'\n2. Click on '...'\n3. See error
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ### Expected Behavior
        What you expected to happen.
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      placeholder: Describe what you expected.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ### Screenshots (Optional)
        Add screenshots if applicable.
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      placeholder: Paste links or describe images.
  - type: markdown
    attributes:
      value: |
        ### Environment
  - type: dropdown
    id: os
    attributes:
      label: OS
      options:
        - Windows 11
        - macOS Sonoma
        - Linux
        - Other
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: Version number or build info
